# .circleci/config.yml
# Baseline Compat scan for CircleCI

version: 2.1
jobs:
  baseline-compat-scan:
    docker:
      - image: cimg/node:22.17.0
    steps:
      - checkout
      - run: npm install
      - run: npx ts-node cli/scan.ts demo/
      - store_artifacts:
          path: baseline-report.json
      - store_artifacts:
          path: baseline-report.sarif
      - store_artifacts:
          path: baseline-pr-comment.md
workflows:
  version: 2
  baseline-compat:
    jobs:
      - baseline-compat-scan
